// This is an autogenerated file from running `firebase genkit:flow`.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for categorizing transactions.
 *
 * The flow takes a transaction description as input and returns a predicted category.
 * The flow exports:
 *   - `CategorizeTransactionInput`: The input type for the categorizeTransaction function.
 *   - `CategorizeTransactionOutput`: The output type for the categorizeTransaction function.
 *   - `categorizeTransaction`: An async function that categorizes a transaction.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorySchema = z.enum([
  'Alimentacion',
  'Transporte y/o Gasolina',
  'Compras Casa',
  'Prestamo y Deuda',
  'Compra de Repuestos',
  'Servicios Basicos Luz y Agua',
  'Creditos',
  'Otros Gastos',
  'Sueldo',
  'Servicio Tecnico',
  'Comision Inmobiliaria',
  'Otros Ingresos',
]);

const CategorizeTransactionInputSchema = z.object({
  description: z
    .string()
    .describe('La descripción de la transacción a categorizar.'),
});

export type CategorizeTransactionInput = z.infer<
  typeof CategorizeTransactionInputSchema
>;

const CategorizeTransactionOutputSchema = z.object({
  category: CategorySchema.describe('La categoría predicha para la transacción.'),
});

export type CategorizeTransactionOutput = z.infer<
  typeof CategorizeTransactionOutputSchema
>;

/**
 * Categorizes a transaction based on its description.
 * @param input - The input containing the transaction description.
 * @returns The predicted category for the transaction.
 */
export async function categorizeTransaction(
  input: CategorizeTransactionInput
): Promise<CategorizeTransactionOutput> {
  return categorizeTransactionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'categorizeTransactionPrompt',
  input: {schema: CategorizeTransactionInputSchema},
  output: {schema: CategorizeTransactionOutputSchema},
  prompt: `Eres un experto asesor financiero. Tu tarea es categorizar las transacciones de los usuarios según su descripción.

  Las posibles categorías son:
  - Alimentacion
  - Transporte y/o Gasolina
  - Compras Casa
  - Prestamo y Deuda
  - Compra de Repuestos
  - Servicios Basicos Luz y Agua
  - Creditos
  - Otros Gastos
  - Sueldo
  - Servicio Tecnico
  - Comision Inmobiliaria
  - Otros Ingresos

  Dada la siguiente descripción de la transacción:
  Descripción: {{{description}}}

  Determina la categoría más apropiada para esta transacción. Devuelve el nombre de la categoría exactamente como aparece en la lista anterior.
  `,
});

const categorizeTransactionFlow = ai.defineFlow(
  {
    name: 'categorizeTransactionFlow',
    inputSchema: CategorizeTransactionInputSchema,
    outputSchema: CategorizeTransactionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
